version: '3.4'
services:
  v2ray:
    image: v2ray/official
    ports:
      - 80:10086
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy: 
        condition: on-failure
    volumes:
      - /root/gfw_config/v2ray/config_netease.json:/etc/v2ray/v2ray.json
