version: "3.4"
services:

  trojan-server:
    image: teddysun/trojan:1.16.0
    ports:
      - 4443:443
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    volumes:
      - ~/gfw_config/trojan/config:/config
      - ~/gfw_config/trojan/cert:/tmp
